import Foundation

extension APIXU {
    public enum Language: String {
        case arabic = "ar"
        case bengali = "bn"
        case bulgarian = "bg"
        case chineseSimplified = "zh"
        case chineseTraditional = "zh_tw"
        case czech = "cs"
        case danish = "da"
        case dutch = "nl"
        case english = "en"
        case finnish = "fi"
        case french = "fr"
        case german = "de"
        case greek = "el"
        case hindi = "hi"
        case hungarian = "hu"
        case italian = "it"
        case japanese = "ja"
        case javanese = "jv"
        case korean = "ko"
        case mandarin = "zh_cmn"
        case marathi = "mr"
        case polish = "pl"
        case portuguese = "pt"
        case punjabi = "pa"
        case romanian = "ro"
        case russian = "ru"
        case serbian = "sr"
        case sinhalese = "si"
        case slovak = "sk"
        case spanish = "es"
        case swedish = "sv"
        case tamil = "ta"
        case telugu = "te"
        case turkish = "tr"
        case ukranian = "uk"
        case urdu = "ur"
        case vietnamese = "vi"
        case shanghainese = "zh_wuu"
        case xiang = "zh_hsn"
        case cantonese = "zh_yue"
        case zulu = "zu"
    }
}
